"""add chunk columns to embeddings

Revision ID: b0636226f4c7
Revises: 01bf7c4c573f
Create Date: 2026-09-15 16:23:32.692381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0636226f4c7'
down_revision: Union[str, Sequence[str], None] = '01bf7c4c573f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('repository', sa.String(length=255), nullable=True))
    op.add_column('embeddings', sa.Column('file_path', sa.String(length=1000), nullable=True))
    op.add_column('embeddings', sa.Column('start_line', sa.Integer(), nullable=True))
    op.add_column('embeddings', sa.Column('end_line', sa.Integer(), nullable=True))
    op.add_column('embeddings', sa.Column('symbol_name', sa.String(length=255), nullable=True))
    op.create_index('ix_embeddings_repository_model', 'embeddings', ['repository', 'model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_repository_model', table_name='embeddings')
    op.drop_column('embeddings', 'symbol_name')
    op.drop_column('embeddings', 'end_line')
    op.drop_column('embeddings', 'start_line')
    op.drop_column('embeddings', 'file_path')
    op.drop_column('embeddings', 'repository')
    # ### end Alembic commands ###
